import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useRouter } from "next/router";
import { parseCookies, setCookie, destroyCookie } from "nookies";

export default function Home({ nameCookie, emailCookie }) {
  const router = useRouter()

  const logout = async () => {
    console.log('log out')
    const res = await fetch('/api/auth/logout')
    console.log(res)
    router.reload()
 
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome</h1>
      <p>{nameCookie}</p>
      <p>{emailCookie}</p>
      <button onClick={logout}>Logout</button>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  // const res = await fetch('http://localhost:3000/api/auth/loginstatus')

  // const data = await res.json()

  // console.log(data)

  const cookies = parseCookies(ctx);
  const nameCookie = cookies.name
  const emailCookie = cookies.email


  if (!cookies.jwt) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }

  return {
    props: {
      nameCookie,
      emailCookie
    },
  };
}

// export async function getServerSideProps({req}) {

//   const res = await fetch('http://localhost:1337/api/users', {
//     method: 'GET',
//     headers: {
//         Authorization: `Bearer ${process.env.STRAPI_API_KEY}`
//     }
//     })

//   const data = await res.json()

//   // const loginInfo = {
//   //     identifier: 'test@gmail.com',
//   //     password: 'password'
//   // }

//   // const login = await fetch('http://localhost:1337/api/auth/local', {
//   //   method: "POST",
//   //   headers: {
//   //     'Accept': 'application/json',
//   //     'Content-Type': 'application/json'
//   //   },
//   //   body: JSON.stringify(loginInfo)
//   // })

//   // const loginResponse = await login.json()

//     const login = await fetch('http://localhost:3000/api/auth/login', {
//       method: 'POST',
//       body: {username: 'test@gmail.com', password: 'password'}
//     })

//   // axios.post('http://localhost:1337/api/auth/local', loginInfo)
//   // .then(response => {
//   //   //Handle Success
//   //   console.log('Well done!');
//   //   console.log(response.data.user);
//   //   console.log(response.data.jwt);
//   // })
//   // .catch(error => {
//   //   //Handle Error
//   //   console.log('An error occured:', error.response)
//   // })

//   return {
//     props: {
//       data,
//       authData: 'loginResponse'
//     }
//   }
// }
